package fr.satiscraftoryteam.satiscraftory.common.network.stream_codecs;

import io.netty.buffer.ByteBuf;
import net.minecraft.network.codec.ByteBufCodecs;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import org.jetbrains.annotations.NotNull;

public class SatisByteBufCodecs {

    //TODO: is this correct? generated by copilot
    public static StreamCodec<ByteBuf, Item[]> ITEMS_ARRAY = new StreamCodec<>() {
        public Item @NotNull [] decode(ByteBuf p_320813_) {
            int size = p_320813_.readInt();
            Item[] items = new Item[size];
            for (int i = 0; i < size; i++) {
                items[i] = ByteBufCodecs.fromCodec(ItemStack.CODEC).decode(p_320813_).getItem();
            }
            return items;
        }

        public void encode(ByteBuf byteBuf, Item[] itemList) {
            byteBuf.writeInt(itemList.length);
            for (Item item : itemList) {
                if (item != null)
                    ByteBufCodecs.fromCodec(ItemStack.CODEC).encode(byteBuf, item.getDefaultInstance());
                else
                    ByteBufCodecs.fromCodec(ItemStack.CODEC).encode(byteBuf, ItemStack.EMPTY);
            }
        }
    };
}
