package fr.satiscraftoryteam.satiscraftory.common.network.stream_codecs;

import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import io.netty.buffer.ByteBuf;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.codec.ByteBufCodecs;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import org.jetbrains.annotations.NotNull;

public class SatisByteBufCodecs {
    //some really dark magic here
    public static final Codec<ItemStack> ITEM_STACK_CODEC = Codec.lazyInitialized(() ->
        RecordCodecBuilder.create(
                instance -> instance.group(
                        BuiltInRegistries.ITEM.holderByNameCodec().fieldOf("item").forGetter(ItemStack::getItemHolder),
                        Codec.INT.fieldOf("count").forGetter(ItemStack::getCount)
                ).apply(instance, ItemStack::new)
        )
    );

    //TODO: is this correct? generated by copilot (goldor: no it crashes the game, see error below - Should be fix by dark magic above )
    // Caused by: io.netty.handler.codec.EncoderException: Failed to encode: Value must be within range [1;99]: 0; Item must not be minecraft:air 0 minecraft:air
    public static StreamCodec<ByteBuf, Item[]> ITEMS_ARRAY = new StreamCodec<>() {
        public Item @NotNull [] decode(ByteBuf p_320813_) {
            int size = p_320813_.readInt();
            Item[] items = new Item[size];
            for (int i = 0; i < size; i++) {
                items[i] = ByteBufCodecs.fromCodec(ITEM_STACK_CODEC).decode(p_320813_).getItem();
            }
            return items;
        }

        public void encode(ByteBuf byteBuf, Item[] itemList) {
            byteBuf.writeInt(itemList.length);
            for (Item item : itemList) {
                if (item != null)
                    ByteBufCodecs.fromCodec(ITEM_STACK_CODEC).encode(byteBuf, item.getDefaultInstance());
                else
                    ByteBufCodecs.fromCodec(ITEM_STACK_CODEC).encode(byteBuf, ItemStack.EMPTY);
            }
        }
    };
}
